### ISSUE TITLE
实验结果问题

### ISSUE THREAD

**Issue by yuquanle** [jx00109/sentence2vec#3]
你好，最近用你的代码复现了一下实验，但是测试结果和你博客那个结果相差比较远，我不知道是哪里出了问题，希望你能指点下。 我用的词向量是GoogleNews-vectors-negative300.bin.gz（也试过glove）。词频字典是作者源码文件夹下的enwiki_vocab_min200.txt文件，我用这个按照（语料库中w出现的次数/语料库中的总词数）构建了词频字典。

我的实验结果如下图：

![1 jpg](https://user-images.githubusercontent.com/20789703/31307928-b8106aca-ab9f-11e7-9113-b9265f22ebe7.png)

**Comment by jx00109** [comment]
已邮件回复，解决。
